apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: assignment2
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: assignment2
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306